spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/s74_vouchers}
    username: ${DATABASE_USERNAME:s74_vouchers}
    password: ${DATABASE_PASSWORD:s74_vouchers}
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}

logging:
  level:
    cz.s74.vouchers: DEBUG
